version: '3.8'
services:
  postgresql:
    container_name: dont-scroll-postgres
    image: cube-postgres:13
    restart: always
    environment:
      POSTGRES_USER: dont_scroll
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - dont_scroll_network
    ports:
      - "5432:5432"

  pgadmin:
    container_name: dont-scroll-pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dont@scroll.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - dont_scroll_network
    ports:
      - "8080:80"
    depends_on:
      - postgresql

volumes:
  postgresql_data:
  pgadmin_data:

networks:
  dont_scroll_network:
    driver: bridge
