SLACK_SIGNING_SECRET="<YOUR SIGING KEY>"
BOT_USER_OAUTH_TOKEN="<YOUR AUTH TOKEN>"
SLACK_APP_TOKEN="<YOUR BOT TOKEN>"
CHANNEL_ID="<YOUR BOT TOKEN>"
DB_HOST = "127.0.0.1"
DB_PORT = 5432
DB_USER = "dont_scroll"
DB_PASSWORD = "passwd"
DB_NAME = "dont_scroll_db"
DB_TABLE = "public.slack_message"
