SLACK_SIGNING_SECRET="YOUR-SIGING-KEY"
BOT_USER_OAUTH_TOKEN="xoxb-YOUR-BOT-TOKEN"
SLACK_APP_TOKEN="xapp-YOUR-APP-TOKEN"
CHANNEL_ID="YOUR-CHANNEL-ID"
DB_HOST = "127.0.0.1"
DB_PORT = 5432
DB_USER = "dont_scroll"
DB_PASSWORD = "secret"
DB_NAME = "dont_scroll_db"
DB_TABLE = "public.slack_message"
